name: CI - RideNow

on:
  push:
    branches: [ main, Fabrizio, Ari, Brandom, Charly, darlyn ]
  pull_request:
    branches: [ main ]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24'
      - name: Instalar dependencias backend
        run: cd backend && npm install
      - name: Verificar instalacion backend
        run: cd backend && npm install --dry-run

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24'
      - name: Instalar dependencias frontend
        run: cd frontend && npm install
      - name: Verificar build frontend
        run: cd frontend && npm run build